--MANAGER TABLE
CREATE TABLE MANAGER(MNO NUMBER(1),MNAME varchar2(25));

INSERT INTO MANAGER(MNO,MNAME) VALUES(1,'Ashish');
INSERT INTO MANAGER(MNO,MNAME) VALUES(2,'Ripal');
INSERT INTO MANAGER(MNO,MNAME) VALUES(3,'Jignasha');

--EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (EMP_NO NUMBER(3),EMP_NAME varchar2(30),EMP_SAL NUMBER(8,2),EMP_COMM NUMBER(6,1),DEPT_NO NUMBER(3));

INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(101,'Smith',800,NULL,20);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(102,'Snehal',1600,300,25);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(103,'Adama',1100,0,20);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(104,'Aman',3000,NULL,15);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(105,'Anita',5000,50000,10);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(106,'Sneha',2450,24500,10);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(107,'Anamika',2975,NULL,30);
