CREATE TABLE DEPOSIT (ACTNO VARCHAR2(5),CNAME VARCHAR2(18) ,
BNAME VARCHAR2(18) , AMOUNT NUMBER(8,2),ADATE DATE);
INSERT INTO DEPOSIT VALUES('100','ANIL','VRCE',1000.00,'1-MAR-95');
INSERT INTO DEPOSIT VALUES('101','SUNIL','AJNI',5000,'4-JAN-96');
INSERT INTO DEPOSIT VALUES('102','MEHUL','KAROLNAGH',3500.00,'17-NOV-95');                           
INSERT INTO DEPOSIT VALUES('104','MADHURI','CHANDI',1200.00,'17-DEC-95');
--adding a new column because if there is no 'dharampeth' in deposit table as the same order in branch table then it will not show an output
INSERT INTO DEPOSIT VALUES('112','TINA','DHARAMPETH',4000.00,'15-OCT-95');
INSERT INTO DEPOSIT VALUES('105','PRAMOD','M.G.ROAD',3000.00,'27-MAR-96');
INSERT INTO DEPOSIT VALUES('106','SANDIP','ANDHERI',2000.00,'31-MAR-96');
INSERT INTO DEPOSIT VALUES('107','SHIVANI','VIRAR',1000.00,'5-SEP-95');
INSERT INTO DEPOSIT VALUES('108','KRANTI','NEHRU PLACE',5000.00,'2-JULY-95');
INSERT INTO DEPOSIT VALUES('109','MINU','POWAI',7000.00,'10-AUG-95');
CREATE TABLE BRANCH(BNAME VARCHAR2(18),CITY VARCHAR2(18));
INSERT INTO BRANCH VALUES('VRCE','NAGPUR');
INSERT INTO BRANCH VALUES('AJNI','NAGPUR');
INSERT INTO BRANCH VALUES('KAROLNAGH','DELHI');
INSERT INTO BRANCH VALUES('CHANDI','DELHI');
INSERT INTO BRANCH VALUES('DHARAMPETH','NAGPUR');
INSERT INTO BRANCH VALUES('M.G.ROAD','BANGALORE');
INSERT INTO BRANCH VALUES('ANDHERI','BOMBAY');
INSERT INTO BRANCH VALUES('VIRAR','BOMBAY');
INSERT INTO BRANCH VALUES('NEHRU PLACE','DELHI');
INSERT INTO BRANCH VALUES('POWAI','BOMBAY');
SELECT D.ACTNO,B.BNAME FROM DEPOSIT D 
INNER JOIN BRANCH B ON D.BNAME = B.BNAME;
SELECT D.ACTNO,B.CITY FROM DEPOSIT D 
LEFT JOIN BRANCH B ON D.BNAME = B.BNAME;

SELECT D.ACTNO,B.BNAME FROM DEPOSIT D 
RIGHT JOIN BRANCH B ON D.BNAME = B.BNAME;

CREATE TABLE BORROW(LOANNO VARCHAR2(5), CNAME VARCHAR2(18),
BNAME VARCHAR2(18), AMOUNT NUMBER (8,2));
INSERT INTO BORROW VALUES('201','ANIL','VRCE',1000.00);
INSERT INTO BORROW VALUES('206','MEHUL','AJNI',5000.00);
INSERT INTO BORROW VALUES('311','SUNIL','DHARAMPETH',3000.00);
INSERT INTO BORROW VALUES('321','MADHURI','ANDHERI',2000.00);
INSERT INTO BORROW VALUES('375','PRAMOD','VIRAR',8000.00);
INSERT INTO BORROW VALUES('481','KRANTI','NEHRU PLACE',3000.00);
CREATE TABLE BRANCH(BNAME VARCHAR2(18),CITY VARCHAR2(18));
INSERT INTO BRANCH VALUES('VRCE','NAGPUR');
INSERT INTO BRANCH VALUES('AJNI','NAGPUR');
--INSERT INTO BRANCH VALUES('KAROLNAGH','DELHI');
--INSERT INTO BRANCH VALUES('CHANDI','DELHI');
INSERT INTO BRANCH VALUES('DHARAMPETH','NAGPUR');
--INSERT INTO BRANCH VALUES('M.G.ROAD','BANGALORE');
INSERT INTO BRANCH VALUES('ANDHERI','BOMBAY');
INSERT INTO BRANCH VALUES('VIRAR','BOMBAY');
INSERT INTO BRANCH VALUES('NEHRU PLACE','DELHI');
--INSERT INTO BRANCH VALUES('POWAI','BOMBAY');
SELECT B.CNAME,B.BNAME 
FROM BORROW B
FULL JOIN BRANCH BR 
ON B.BNAME = BR.BNAME;
SELECT * FROM BRANCH 
NATURAL JOIN BORROW;
SELECT * FROM BORROW 
NATURAL JOIN BRANCH;
