--USING ALTER TABLE, UPDATE AND TRUNCATE
CREATE TABLE BRANCH(BNAME VARCHAR2(18),CITY VARCHAR2(18));
INSERT INTO BRANCH VALUES('VRCE','NAGPUR');
SELECT * FROM BRANCH;
INSERT INTO BRANCH VALUES('AJNI','NAGPUR');
INSERT INTO BRANCH VALUES('KAROLNAGH','DELHI');
INSERT INTO BRANCH VALUES('CHANDI','DELHI');
INSERT INTO BRANCH VALUES('DHARAMPETH','NAGPUR');
INSERT INTO BRANCH VALUES('M.G.ROAD','BANGALORE');
INSERT INTO BRANCH VALUES('ANDHERI','BOMBAY');
INSERT INTO BRANCH VALUES('VIRAR','BOMBAY');
INSERT INTO BRANCH VALUES('NEHRU PLACE','DELHI');
INSERT INTO BRANCH VALUES('POWAI','BOMBAY');
ALTER TABLE BRANCH ADD(USER_CAPACITY NUMBER(4));
UPDATE BRANCH SET USER_CAPACITY=300 WHERE BNAME='CHANDI';
SELECT * FROM BRANCH;
UPDATE BRANCH SET USER_CAPACITY=2500 WHERE CITY='BOMBAY';
SELECT * FROM BRANCH;
TRUNCATE TABLE BRANCH;
SELECT * FROM BRANCH;

