--USING PATTERN MATCHING CONDITIONS
CREATE TABLE BRANCH(BNAME VARCHAR2(18),CITY VARCHAR2(18));
INSERT INTO BRANCH VALUES('VRCE','NAGPUR');
SELECT * FROM BRANCH;
INSERT INTO BRANCH VALUES('AJNI','NAGPUR');
INSERT INTO BRANCH VALUES('KAROLNAGH','DELHI');
INSERT INTO BRANCH VALUES('CHANDI','DELHI');
INSERT INTO BRANCH VALUES('DHARAMPETH','NAGPUR');
INSERT INTO BRANCH VALUES('M.G.ROAD','BANGALORE');
INSERT INTO BRANCH VALUES('ANDHERI','BOMBAY');
INSERT INTO BRANCH VALUES('VIRAR','BOMBAY');
INSERT INTO BRANCH VALUES('NEHRU PLACE','DELHI');
INSERT INTO BRANCH VALUES('POWAI','BOMBAY');
SELECT * FROM BRANCH WHERE CITY LIKE('BOMBAY');
SELECT * FROM BRANCH WHERE BNAME LIKE 'A%';
SELECT * FROM BRANCH WHERE CITY LIKE '_A%';
