
CREATE TABLE EMPLOYEE (EMP_NO NUMBER(3),EMP_NAME varchar2(30),EMP_SAL NUMBER(8,2),EMP_COMM NUMBER(6,1),DEPT_NO NUMBER(3));

INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(101,'Smith',800,NULL,20);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(102,'Snehal',1600,300,25);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(103,'Adama',1100,0,20);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(104,'Aman',3000,NULL,15);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(105,'Anita',5000,50000,10);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(106,'Sneha',2450,24500,10);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES(107,'Anamika',2975,NULL,30);

SELECT * FROM EMPLOYEE;
SELECT EMP_NO,EMP_NAME,DEPT_NO FROM EMPLOYEE WHERE DEPT_NO IN (10,20);
SELECT EMP_NO,EMP_NAME,DEPT_NO FROM EMPLOYEE WHERE DEPT_NO BETWEEN 10 AND 20;
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'A_a%';
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE  '_n___' AND EMP_COMM IS NOT NULL;
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '__a%' AND EMP_COMM IS NULL;

CREATE TABLE SUP1 AS SELECT EMP_NO,EMP_NAME FROM EMPLOYEE;
SELECT * FROM SUP1;
CREATE TABLE SUP2 AS SELECT * FROM EMPLOYEE;
SELECT * FROM SUP2;
