--USING "NOT NULL" AND "CHECK" CONSTRAINT
CREATE TABLE CLIENT_MASTER(CLIENTNO VARCHAR2(3) NOT NULL, NAME VARCHAR(20) NOT NULL, ADRESS1 VARCHAR2(30));
INSERT INTO CLIENT_MASTER VALUES('101','NENE','NEWYORK CITY');
SELECT * FROM CLIENT_MASTER;
INSERT INTO CLIENT_MASTER VALUES(NULL,'HARUHI','TOKYO');
--IF AN ERROR SHOWS, IT MEANS NOT NULL CONSTRAINT IS IMPLEMENTED SUCCESSFULLY
CREATE TABLE IAMNOTAMINOR (NAME VARCHAR2(20),AGE NUMBER(3) CHECK(AGE>18),BDAY DATE,ID_NUM VARCHAR2(10));
INSERT INTO IAMNOTAMINOR VALUES('SOOHA',19,'15-JUL-06','1234');
SELECT * FROM IAMNOTAMINOR;
INSERT INTO IAMNOTAMINOR VALUES('NENE',13, '1-JAN-12','546');
SELECT * FROM IAMNOTAMINOR;
--CHECK CONSTRAINT TAKES LONGER TIME TO EXECUTE THAN DINOSAUR EXTINCTION HAPPENING
--SO IT'S BETTER TO AVOID USING THIS CONSTRAINT 
DROP TABLE CLIENT_MASTER;
CREATE TABLE CLIENT_MASTER(CLIENTNO VARCHAR2(3) NOT NULL, NAME VARCHAR(20) DEFAULT 'GUEST', ADRESS1 VARCHAR2(30));
INSERT INTO CLIENT_MASTER VALUES('101','NENE','NEWYORK CITY');
SELECT * FROM CLIENT_MASTER;
INSERT INTO CLIENT_MASTER VALUES('102' ,DEFAULT,'TOKYO');
SELECT * FROM CLIENT_MASTER;
