CREATE TABLE DEPOSIT (ACTNO VARCHAR2(5),CNAME VARCHAR2(18) ,
BNAME VARCHAR2(18) , AMOUNT NUMBER(8,2),ADATE DATE);
INSERT INTO DEPOSIT VALUES('100','ANIL','VRCE',1000.00,'1-MAR-95');
INSERT INTO DEPOSIT VALUES('101','SUNIL','AJNI',5000,'4-JAN-96');
INSERT INTO DEPOSIT VALUES('102','MEHUL','KAROLBAGH',3500.00,'17-NOV-95');                           
INSERT INTO DEPOSIT VALUES('104','MADHURI','CHANDI',1200.00,'17-DEC-95');
INSERT INTO DEPOSIT VALUES('105','PRAMOD','M.G.ROAD',3000.00,'27-MAR-96');
INSERT INTO DEPOSIT VALUES('106','SANDIP','ANDHERI',2000.00,'31-MAR-96');
INSERT INTO DEPOSIT VALUES('107','SHIVANI','VIRAR',1000.00,'5-SEP-95');
INSERT INTO DEPOSIT VALUES('108','KRANTI','NEHRU PLACE',5000.00,'2-JULY-95');
INSERT INTO DEPOSIT VALUES('109','MINU','POWAI',7000.00,'10-AUG-95');
SELECT TRUNC(ADATE, 'MONTH') FROM DEPOSIT;
SELECT TRUNC(ADATE, 'DD') FROM DEPOSIT;
SELECT * FROM DEPOSIT;
INSERT INTO DEPOSIT VALUES('100','ANIL','VRCE',1000.00,'1-03-95');
SELECT * FROM DEPOSIT;
SELECT TRUNC(TO_DATE(ADATE,'DD-MON-YY'), 'MONTH') AS NewMonth FROM DEPOSIT;
--HERE IT IS MONTH THAT IS WHY IT WILL RETURN FIRST DAY OF EVERY MONTH !
SELECT TRUNC(TO_DATE('05-SEP-95','DD-MON-YYYY'), 'YYYY') AS NewYear FROM DEPOSIT;
--HERE IT WILL RETURN FIRST DAY OF THE YEAR 
SELECT TRUNC(DATE '10-AUG-95', 'MON') AS NewMonth FROM DEPOSIT;
--SOMETIMES THE VALUES ARE IN STRING FORMAT 
--HENCE TO WE NEED TO CONVERT THEM INTO DATE FORMAT FIRST THEN APPLY TRUNC
SELECT TO_NUMBER('AMOUNT','9999.99') FROM DEPOSIT;
ALTER TABLE DEPOSIT MODIFY AMOUNT NUMBER(9, 2);
SELECT TO_CHAR(AMOUNT, '9,999.99') FROM deposit;
SELECT TO_NUMBER(AMOUNT,'9999.99') FROM DEPOSIT;
SELECT * FROM DEPOSIT;
SELECT TO_DATE(ADATE,'DD-MM-YY') AS NEWDATE FROM DEPOSIT;
SELECT INSTR('SHIVANI','A') FROM DEPOSIT;
