--USING CREATE TABLE, INSERT INTO AND VIEWING INSERTED DATA
CREATE TABLE CUSTOMERS (CNAME VARCHAR2(19) ,CITY VARCHAR2(18));
INSERT INTO CUSTOMERS VALUES('SNE', 'ANK');
INSERT INTO CUSTOMERS VALUES('MYG','DAEGU');
INSERT INTO CUSTOMERS VALUES('BOOBU','BHARUCH');
SELECT * FROM CUSTOMERS;
SELECT CNAME FROM CUSTOMERS WHERE CITY='ANK';
